sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t tragu/docker-react -f Dockerbuild.dev .


script:
  - docker run -e CI=true USERNAME/docker-react npm run test